### ISSUE TITLE
Start documentation

### ISSUE THREAD

**Issue by tinosulzer** [ImperialCollegeLondon/R2T2#12]
Beyond the README, R2T2 lacks of proper documentation. This should be created and kept updated as R2T2 grows, as usual. Using (expanding) GitHub pages is probably the easiest solution, as the project is not likely to become as big and complex as to need a platform like Read the Docs. 

In any case, if the documentation is correctly setup in GitHub pages, it should not be complicated to port it to RtD is/when needed.

**Comment by rgaiacs** [comment]
Any reason to not port it to Read the Docs as part of the eLife Sprint?

**Comment by dalonsoa** [comment]
Not at all! I just thought it was a bit overkilling for a project this size, but it is absolutely fine to go straight for it.

**Comment by rgaiacs** [comment]
We can close this one.
