### ISSUE TITLE
Suggestion: Put dev dependencies into requirements.dev.txt with specific versions

### ISSUE THREAD

**Issue by de-code** [ImperialCollegeLondon/R2T2#59]
Currently the `setup.py` contains the following dev dependencies but no versions: ["pytest", "pytest-flake8", "pytest-mypy", "pytest-cov"]

The version is necessary to make it re-producible. (There are sometimes breaking changes, e.g. new linting rules)

Putting it into a `requirements.dev.txt` will make it easy to review the dependencies and let tools like Dependabot keep them up-to-date.

**Comment by jezcope** [comment]
This is sensible. Other options could be:

- Add a `Pipfile` and `Pipfile.lock` and use [pipenv](https://pipenv.readthedocs.io/)
- Move dependencies to `pyproject.toml` and use [Poetry](https://python-poetry.org/docs/basic-usage/) with `poetry.lock`

On balance I probably prefer Poetry because it supports the whole dependency management and packaging workflow and doesn't add so many extra files, but I'm happy to go with the general consensus.

**Comment by jezcope** [comment]
Worth adding that making use of Dependabot is a good idea, and it supports all three of the above solutions.

**Comment by dalonsoa** [comment]
Yes, it makes sense to use this - and Dependabot; I dind't know about it. I am also more in favour of poetry. I have sue it in the paset and seems quite elegant.

**Comment by jezcope** [comment]
I'm happy to take this on for the next session (day 2 session 3). I think that would be:

- [x] Add necessary configuration & dependencies to `pyproject.toml`
- [x] Update developer documentation to include Poetry
- [ ] Check Dependabot is working (I think this is automatic on GitHub's side)
- [x] Make sure CI isn't broken
- [x] *Optional: move other config into `pyproject.toml` as per #55*

**Comment by de-code** [comment]
I used `Pipenv` before and went back to plain requirements files. What I like about plain requirements files is that they are simple and don't require another tool to be installed. e.g. if you use `poetry` that needs to be installed first. (`pip` is usually already installed)

**Comment by dalonsoa** [comment]
I'm closing this as it is obsolete after #67. @jezcope , I've open #78 to check the Dependabot.
