### ISSUE TITLE
Suggestion: add Makefile

### ISSUE THREAD

**Issue by de-code** [ImperialCollegeLondon/R2T2#60]
a simple Makefile would make it easier to use for development.

It could have make targets for things like initial setup (creating virtual environment), installing / updating dependencies, running or watching tests etc.

One can easily see the available Make targets and there is auto-completion available.

**Comment by dalonsoa** [comment]
I'm not in favour of using a makefile, to be honest. I think there are other, more pythonic ways of doing this - poetry, as mentioned in #59 , or [tox](https://tox.readthedocs.io/en/latest/) - that do not require to install an external (not python related) tool.

**Comment by jezcope** [comment]
To go fully Pythonic there are tools like [SCons](https://scons.org/) and [doit](https://pydoit.org/) but before going down that road it would be useful to think about what tasks couldn't be handled by an existing tool like poetry. The advantage of doing that is that the UI is familiar to anyone who's already used poetry in another project, whereas with our own Makefile people can list and auto-complete the targets but will still need to look in the Makefile to see what it's actually going to do.

**Comment by de-code** [comment]
One advantage of `make` is that it is often also already installed and many people are familiar with it. There are so many other tools that can be used. My suggestion would be to use Makefile but you could use other tools under the hood and you could switch tools. Then people can interact with them directly. But you always have that one interface to do the main tasks. I wouldn't suggest to do anything complicated with Makefiles, just use it as a documentation and short cut of the common tasks.

**Comment by dalonsoa** [comment]
Not in Windows and not by default in some Linux systems. I am still not convinced at all with Makefiles. I feel they try to do too many things. But if there's a general consensus about it...

**Comment by rgaiacs** [comment]
I'm against use `make` here. Some tasks you probably only have to do once (for example, create a development virtual environment) and people might want to use different tools for it (for example, conda vs venv). For other tasks, you could have your own script (Python or Shell).

**Comment by de-code** [comment]
Closing as I seem to be the only person in favour of this.
