### ISSUE TITLE
Rename "master" branch

### ISSUE THREAD

**Issue by jezcope** [ImperialCollegeLondon/R2T2#63]
I think most people are familiar with the context of this now but for those who aren't here's some [background on why it's important and how to do it](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx). GitHub will be changing their default from `master` to `main` soon, and GH Organisation admins can already opt-in to the new default.

Right now this is a very simple change to make because all of our work is going to `develop` rather than `master`.

**Comment by tinosulzer** [comment]
Done
